import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        surface: {
          DEFAULT: "var(--surface)",
          dim: "var(--surface-dim)",
          bright: "var(--surface-bright)",
          variant: "var(--surface-variant)",
          "container-lowest": "var(--surface-container-lowest)",
          "container-low": "var(--surface-container-low)",
          container: "var(--surface-container)",
          "container-high": "var(--surface-container-high)",
          "container-highest": "var(--surface-container-highest)",
        },
        "on-surface": {
          DEFAULT: "var(--on-surface)",
          variant: "var(--on-surface-variant)",
        },
        "on-primary": "var(--on-primary)",
        "inverse-surface": "var(--inverse-surface)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        outline: {
          DEFAULT: "var(--outline)",
          variant: "var(--outline-variant)",
        },
        "surface-tint": "var(--surface-tint)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--on-primary)",
          container: "var(--primary-container)",
          "container-foreground": "var(--on-primary-container)",
          fixed: "var(--primary-fixed)",
          "fixed-dim": "var(--primary-fixed-dim)",
          "fixed-foreground": "var(--on-primary-fixed)",
          "fixed-variant": "var(--on-primary-fixed-variant)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--on-secondary)",
          container: "var(--secondary-container)",
          "container-foreground": "var(--on-secondary-container)",
          fixed: "var(--secondary-fixed)",
          "fixed-dim": "var(--secondary-fixed-dim)",
          "fixed-foreground": "var(--on-secondary-fixed)",
          "fixed-variant": "var(--on-secondary-fixed-variant)",
        },
        tertiary: {
          DEFAULT: "var(--tertiary)",
          foreground: "var(--on-tertiary)",
          container: "var(--tertiary-container)",
          "container-foreground": "var(--on-tertiary-container)",
          fixed: "var(--tertiary-fixed)",
          "fixed-dim": "var(--tertiary-fixed-dim)",
          "fixed-foreground": "var(--on-tertiary-fixed)",
          "fixed-variant": "var(--on-tertiary-fixed-variant)",
        },
        error: {
          DEFAULT: "var(--error)",
          foreground: "var(--on-error)",
          container: "var(--error-container)",
          "container-foreground": "var(--on-error-container)",
        },
        "deep-forest": "var(--deep-forest)",
        "vibrant-clay": "var(--vibrant-clay)",
        "warm-surface": "var(--warm-surface)",
        "muted-sage": "var(--muted-sage)",
      },
      fontFamily: {
        display: ["var(--font-libre-caslon)", "serif"],
        headline: ["var(--font-libre-caslon)", "serif"],
        body: ["var(--font-roboto)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
        "display-xl": ["var(--font-libre-caslon)", "serif"],
        "display-xl-mobile": ["var(--font-libre-caslon)", "serif"],
        "headline-lg": ["var(--font-libre-caslon)", "serif"],
        "headline-lg-mobile": ["var(--font-libre-caslon)", "serif"],
        "headline-md": ["var(--font-libre-caslon)", "serif"],
        "body-lg": ["var(--font-roboto)", "sans-serif"],
        "body-md": ["var(--font-roboto)", "sans-serif"],
        "label-bold": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["84px", { lineHeight: "92px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-xl-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      spacing: {
        base: "var(--base)",
        gutter: "var(--gutter)",
        "section-gap": "var(--section-gap)",
        "margin-mobile": "var(--margin-mobile)",
        "margin-desktop": "var(--margin-desktop)",
      },
      maxWidth: {
        "container-max": "var(--container-max)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
